# Generated by Django 3.1.7 on 2021-10-29 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211029_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfTask', models.DateField(default=datetime.date.today)),
                ('Status', models.CharField(choices=[('Not Started', 'Not Started'), ('Starting', 'Starting'), ('On Hold', 'On Hold'), ('Almost Done', 'Almost Done'), ('Done', 'Done')], default='Not Started', max_length=25)),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-dateOfTask'],
            },
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(max_length=20),
        ),
    ]
