# Generated by Django 3.1.7 on 2022-01-25 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220121_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateOfTask',
            field=models.TextField(default=datetime.date.today),
        ),
    ]
